- name: Install fonts
  hosts: workstations
  vars:
    font_dir_linux: /usr/share/fonts/truetype
    font_dir_darwin: /Library/Fonts
    font_dir: "{{ lookup('vars','font_dir_'+ansible_os_family|lower, default=font_dir_linux) }}"
    default_terminal_font: "InconsolataGo Nerd Font 11"
  tasks:
  - name: Check if Fontconfig exists | apt
    ansible.builtin.apt:
      name: fontconfig
      state: present
    when: ansible_os_family == 'Debian'
  - name: Pragmasevka Nerd Font
    block:
    - name: Check for the latest release - Pragmasevka | uri
      uri:
        url: https://api.github.com/repos/shytikov/pragmasevka/releases/latest
        return_content: true
      register: pragmasevka_json
    - name: "Download Pragmasevka - {{ pragmasevka_json.json.tag_name }} | get_url"
      get_url:
        url: "https://github.com/shytikov/pragmasevka/releases/download/{{ pragmasevka_json.json.tag_name }}/Pragmasevka_NF.zip"
        dest: "/tmp/pragmasevkaNF-{{ pragmasevka_json.json.tag_name }}.zip"
        force: true
      register: pragmasevka_download_result
      failed_when: pragmasevka_download_result.status_code != 200
    - name: Create directory for Pragmasevka | file
      ansible.builtin.file:
        path: "{{ font_dir + '/PragmasevkaNF' }}"
        state: directory
        mode: '0755'
      become: true
      when: pragmasevka_download_result.status_code == 200
    - name: "Install Pragmasevka - {{ pragmasevka_json.json.tag_name }} | unarchive"
      ansible.builtin.unarchive:
        src: "/tmp/pragmasevkaNF-{{ pragmasevka_json.json.tag_name }}.zip"
        dest: "{{ font_dir + '/PragmasevkaNF/'}}"
      become: true
  - name: Ubuntu Sans Nerd Font
    block:
    - name: Check for the latest release - Ubuntu Sans Nerd Font | uri
      uri:
        url: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest
        return_content: true
      register: ubuntusans_nerd_json
    - name: "Download UbuntuSans Nerd Font - {{ ubuntusans_nerd_json.json.tag_name }} | get_url"
      get_url:
        url: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ubuntusans_nerd_json.json.tag_name}}/UbuntuSans.zip"
        dest: "/tmp/ubuntusans_nerd-{{ubuntusans_nerd_json.json.tag_name}}.zip"
        force: true
      register: ubuntusans_download_result
      failed_when: ubuntusans_download_result.status_code != 200
    - name: Create directory for Ubuntu Sans Nerd | file
      ansible.builtin.file:
        path: "{{ font_dir + '/UbuntuSansNerd' }}"
        state: directory
        mode: '0755'
      become: true
      when: ubuntusans_download_result.status_code == 200
    - name: "Install Ubuntu Sans Nerd Font - {{ ubuntusans_nerd_json.json.tag_name }} | unarchive"
      ansible.builtin.unarchive:
        src: "/tmp/ubuntusans_nerd-{{ ubuntusans_nerd_json.json.tag_name }}.zip"
        dest: "{{ font_dir + '/UbuntuSansNerd/' }}"
      become: true
      when: ubuntusans_download_result.status_code == 200
  - name: Inconsolata Go Nerd Font
    block:
    - name: Check for the latest release - Inconsolata Go Nerd Font | uri
      uri:
        url: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest
        return_content: true
      register: inconsolatago_nerd_json
    - name: "Download Inconsolata Go Nerd Font - {{ inconsolatago_nerd_json.json.tag_name }} | get_url"
      get_url:
        url: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ inconsolatago_nerd_json.json.tag_name }}/InconsolataGo.zip"
        dest: "/tmp/inconsolatago_nerd-{{ inconsolatago_nerd_json.json.tag_name }}.zip"
        force: true
      register: inconsolatago_download_result
      failed_when: inconsolatago_download_result.status_code != 200
    - name: Create directory for Inconsolata Go Nerd | file
      ansible.builtin.file:
        path: "{{ font_dir + '/InconsolataGoNerd' }}"
        state: directory
        mode: '0755'
      become: true
      when: inconsolatago_download_result.status_code == 200
    - name: "Install Inconsolata Go Nerd Font - {{ inconsolatago_nerd_json.json.tag_name }} | unarchive"
      ansible.builtin.unarchive:
        src: "/tmp/inconsolatago_nerd-{{ inconsolatago_nerd_json.json.tag_name }}.zip"
        dest: "{{ font_dir + '/InconsolataGoNerd/' }}"
      become: true
      when: inconsolatago_download_result.status_code == 200
  - name: Refresh Fontconfig cache | shell
    become: true
    become_user: "{{ item }}"
    ansible.builtin.shell:
      cmd: "fc-cache -f"
    loop: "{{ users }}"
    when: ansible_system == "Linux"
  - name: "Set default font to \"{{ default_terminal_font }}\" on linux | dconf"
    become: true
    become_user: "{{ item }}"
    community.general.dconf:
      key: "/org/gnome/desktop/interface/monospace-font-name"
      value: "'{{ default_terminal_font }}'"
      state: present
    loop: "{{ users }}"
    when: ansible_system == 'Linux'
