- name: Install homebrew on OSX computers
  hosts: osx
  tasks:
  - name: Check for the latest release | uri
    uri:
      url:  https://api.github.com/repos/Homebrew/brew/releases/latest
      return_content: true
    register: homebrew_json
  - name: "Download latest Homebrew pkg - {{ homebrew_json.json.tag_name }} | get_url"
    get_url:
      url: "https://github.com/Homebrew/brew/releases/download/{{homebrew_json.json.tag_name}}/Homebrew-{{ homebrew_json.json.tag_name }}.pkg"
      dest: /tmp/homebrew-latest.pkg
  - name: Install downloaded pkg | cmd
    ansible.builtin.command:
      cmd: installer -pkg /tmp/homebrew-latest.pkg -target /
    become: true
  - name: Configure repository origin | cmd
    ansible.builtin.command:
      cmd: 'git -C "/opt/homebrew" remote add origin https://github.com/Homebrew/brew'
    ignore_errors: true
    become: true
  - name: Change permissions of /opt/homebrew | file
    become: true
    ansible.builtin.file:
      path: /opt/homebrew
      state: directory
      mode: g+w
      recurse: yes
      group: admin
  - name: Add exception for dubious ownership in /opt/homebrew | cmd
    ansible.builtin.command:
      cmd: "git config --global --ad safe.directory /opt/homebrew"
    become: true 