- name: Install printers
#  hosts: workstations
  vars:
      # taking the link from european version of Canon website and resolving the redirect via wget
      # temporary measure, in the future i would like to automatically download the latest version of the driver somehow
    driver_lnx: "https://gdlp01.c-wss.com/gds/8/0100007658/40/linux-UFRII-drv-v590-m17n-03.tar.gz"
  tasks:
    - ansible.builtin.include_tasks:
        file: ./install_printer_deb.yaml
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint"
