- name: Install mc on Debian derivatives | apt
  become: true
  ansible.builtin.apt:
    state: latest
    update_cache: true
    name: mc
  register: output
- name: Show output
  debug: msg="{{ output.stdout_lines }}"
- name: Install neovim on Debian derivatives | apt
  become: true
  ansible.builtin.apt:
    state: latest
    update_cache: false
    name: neovim
  register: output
- name: Show output
  debug: msg="{{ output.stdout_lines }}"
- name: Install zsh on Debian derivatives | apt
  become: true
  ansible.builtin.apt:
    state: latest
    update_cache: false
    name: zsh
  register: output
- name: Show output
  debug: msg="{{ output.stdout_lines }}"
- name: Install hwinfo on Debian derivatives | apt
  become: true
  ansible.builtin.apt:
    state: latest
    update_cache: false
    name: hwinfo
  register: output
- name: Show output
  debug: msg="{{ output.stdout_lines }}"
- name: Install inxi on Debian derivatives | apt
  become: true
  ansible.builtin.apt:
    state: latest
    update_cache: false
    name: inxi
  register: output
- name: Show output
  debug: msg="{{ output.stdout_lines }}"
