- name: Install required packages
  hosts: all
  tasks:
  - include: ./required_pkgs_apt.yaml
    when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint"
