- name: Install NextCloud Desktop on Debian derivatives | apt
  hosts: linux
  become: true
  ansible.builtin.apt:
    state: latest
    update_cache: true
    name: mc
  register: output
- name: Show output
  debug: msg="{{ output.stdout_lines }}"
